[project]
name = "graphalgoviz"
version = "0.1.0"
description = ""
authors = [
    {name = "null-route-dev"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "pyside6 (>=6.11.2,<7.0.0)",
    "matplotlib (>=3.11.2,<4.0.0)"
]

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "ruff (>=0.16.8,<0.17.0)",
    "mypy (>=2.3.1,<3.0.0)",
    "uncomment (>=3.7.0,<4.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "domain", from = "src" },
    { include = "application", from = "src" },
    { include = "infrastructure", from = "src" },
    { include = "presentation", from = "src" },
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.mypy]
strict = true
mypy_path = "src"
explicit_package_bases = true
